apiVersion: apps/v1
kind: Deployment
metadata:
  name: cutm-portal-app
  namespace: cutm-portal
  labels:
    app: cutm-portal
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cutm-portal
  template:
    metadata:
      labels:
        app: cutm-portal
    spec:
      containers:
      - name: cutm-portal
        image: cutm-portal:latest
        ports:
        - containerPort: 3000
        envFrom:
        - configMapRef:
            name: cutm-portal-config
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /api/health
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /api/health
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        startupProbe:
          httpGet:
            path: /api/health
            port: 3000
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 10
---
apiVersion: v1
kind: Service
metadata:
  name: cutm-portal-service
  namespace: cutm-portal
spec:
  selector:
    app: cutm-portal
  ports:
  - port: 80
    targetPort: 3000
    protocol: TCP
  type: LoadBalancer
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: cutm-portal-hpa
  namespace: cutm-portal
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: cutm-portal-app
  minReplicas: 2
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
